apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-pod-security-policy
roleRef:
  kind: ClusterRole
  name: default-pod-security-policy
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts
  - kind: Group
    name: system:nodes
    apiGroup: rbac.authorization.k8s.io
