apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-pod-security-policy
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - default
